blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/snw-mint/fluent-new-tab/discussions
    about: Got questions? Use Discussions for general inquiries and support.
