name: 🚀 Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: "Describe your idea briefly..."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Details (Optional)
      placeholder: "Any extra context, mockups, or examples?"