name: Gemini Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR Agent Action
        uses: the-pr-agent/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.GEMINI_KEY }}
          OPENAI_API_BASE: "https://generativelanguage.googleapis.com/v1beta/openai/"
          MODEL: "gemini-3.6-flash"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}